### ISSUE TITLE
Monitor incoming dir for .zip's and unpack them automatically?

### ISSUE THREAD

**Issue by bacon-cheeseburger** [Tensai75/AddNZBs.py#3]
Hi, this isn't a bug but since there isn't a discussion tab....

As I understand it, this extension monitors the contents of downloaded items, unpacks zips, and auto-adds any resulting .nzb's into the queue. Would it be possible to expand this script to also monitor the incoming dir (NzbDir) for .zip's and perform the same function? 

My use-case is that I typically download zipped .nzb's on a different pc and saves them to the import dir I set NzbDir to on the box running nzbget. It's very convenient to have an extension auto-unpack those zips rather than manually doing it. Until now I've used unzip.py (https://github.com/Prinz23/nzbgetpp) but with your extension actively maintained and likely merged into the official repo, I'd like to switch if it has the functionality I've described.

Any thoughts?

**Comment by Tensai75** [comment]
First of all, the AddNZBs script does not scan for packed files and does not unpack them itself. It only scans the download folder after NZBGet has finished post-processing (i.e. unpacking) and then looks for NZB files only.

Secondly, the functionality you describe is a completely different use case (scan script) and should probably be handled by a discrete script, so I won't include it in my AddNZBs post-processing script.

However, I also think that such functionality should be included as a core feature in NZBGet itself (like SABnzbd does it). Since the programme is now being actively maintained again, I would therefore suggest opening an issue on https://github.com/nzbgetcom/nzbget and submitting a feature request.
